PRODUCT_VERSION_MAJOR := 2
PRODUCT_VERSION_MINOR := 7
PRODUCT_VERSION_PATCH := 1
PRODUCT_VERSION_EXTRA :=

CALYXOS_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_PATCH)$(PRODUCT_VERSION_EXTRA)
