PRODUCT_VERSION_MAJOR := 2
PRODUCT_VERSION_MINOR := 8
PRODUCT_VERSION_PATCH := 0
PRODUCT_VERSION_EXTRA :=

ifneq ($(OFFICIAL_BUILD),true)
PRODUCT_VERSION_EXTRA += -UNOFFICIAL
endif

CALYXOS_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_PATCH)$(PRODUCT_VERSION_EXTRA)
